name: Playwright_oreder Tests

# Определение события, запускающего workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # Основные тесты
    - cron: '0 8 * * *'    # Тест создания заказа (в 08:00)

# Определение Задачи(job)
jobs:
  # Основная часть тестов
  test:
    timeout-minutes: 60

    # Уникальный ключ для группы задач предназначен для того, чтобы повторный запуск Джобы вставал в ожидание, не конфликтуая с первым
    concurrency: playwright-tests

    # запуск на виртуальной машине
    runs-on: ubuntu-22.04
    env:
      USER_PASS: ${{ secrets.USER_PASS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TESTMAIL_JSON: ${{ secrets.TESTMAIL_JSON_ALT}}
      TESTMAIL_ADRESS: ${{ secrets.TESTMAIL_ADRESS_ALT}}
      TESTMAIL_JSON_EMPTY: ${{ secrets.TESTMAIL_JSON_EMPTY}}
      TESTMAIL_ADRESS_EMPTY: ${{ secrets.TESTMAIL_ADRESS_EMPTY}}

    steps:

      # Клонирование репозитория
      - uses: actions/checkout@v4

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Установка браузеров
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      # Установка переменной окружения для connection_config.ini
      - name: Set up environment
        run: |
          sed -i 's/{TMS_TOKEN}/${{ secrets.TMS_TOKEN }}/g' connection_config.ini

      # Запуск тестов
      - name: Run tests
        run: pytest --reruns 2 --reruns-delay 3 --alluredir=allure-results

      # Загрузка артефактов
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ github.run_id }}
          path: allure-results/

  # Тест на создание заказа
  order-test:

    # запуск на виртуальной машине
    runs-on: ubuntu-22.04
    if: github.event.schedule == '0 8 * * *' || github.event_name == 'workflow_dispatch'

    # # Уникальный ключ для группы задач предназначен для того, чтобы повторный запуск Джобы вставал в ожидание, не конфликтуая с первым
    # concurrency: playwright-tests

    steps:

      # Клонирование репозитория
      - uses: actions/checkout@v4

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Установка браузеров
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      # Установка переменной окружения для connection_config.ini
      - name: Set up environment
        run: |
          sed -i 's/{TMS_TOKEN}/${{ secrets.TMS_TOKEN }}/g' connection_config.ini

      # Запуск тестов
      - name: Run only test_create_order
        run: pytest --reruns 2 --reruns-delay 3 -m "custom_schedule" --alluredir=allure-results

      # Загрузка артефактов
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ github.run_id }}
          path: allure-results/

  # Обьединение отчетов по всем тестам
  merge-reports:
    needs: [test, order-test]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results
          merge-multiple: true

      # Получение истории прогонов Allure
      - name: Get Allure history
        uses: actions/checkout@v4  # Обновляем до v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Создаем директорию для текущего отчета с timestamp
      - name: Create report directory
        run: |
          mkdir -p gh-pages/history/$(date +%Y%m%d_%H%M%S)
          cp -r gh-pages/history/latest/* allure-results/history/ || true

      # Генерация отчета Allure
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: gh-pages/history/latest
          keep_reports: 20

      # Копируем текущий отчет в директорию с timestamp
      - name: Copy report to timestamped directory
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          cp -r allure-report/* gh-pages/history/$TIMESTAMP/
          cp -r allure-report/* gh-pages/history/latest/

      # Создаем index.html со списком всех отчетов
      - name: Generate index page
        run: |
          cd gh-pages/history
          echo "<html><body><h1>Allure Reports History</h1><ul>" > index.html
          for d in */ ; do
            if [ "$d" != "latest/" ]; then
              echo "<li><a href='./$d'>Report $d</a></li>" >> index.html
            fi
          done
          echo "</ul></body></html>" >> index.html

      # Публикация отчета Allure
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages/history
          keep_files: true

      # Публикация результата прогона в testIT
      # - name: Submit results testIT
      #   if: always()
      #   run: |
      #     pip install testit-cli
      #     #export TMS_TOKEN=${{ secrets.TMS_TOKEN }}
      #     testit results import \
      #       --url https://team-wuas.testit.software/ \
      #       --token ${{ secrets.TMS_TOKEN }} \
      #       --project-id 87c7eb78-be36-4e13-9e36-651ca3d5f060 \
      #       --configuration-id 36238c9d-da5e-4cca-a8c4-f0d8316d3f6b \
      #       --testrun-name "GitHubtestrun" \
      #       --results results/test-results.xml
